name: Metrics

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Workflow 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Most used (with details)
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.languages.details.svg
      #     token: ${{ secrets.ACTIONS_TOKEN }}
      #     base: ""
      #     plugin_languages: yes
      #     plugin_languages_details: bytes-size, percentage
      #     plugin_languages_ignored: javascript
      #     plugin_languages_colors: 0:#00ff00, 1:#ff0000, 2:#0000ff, 3:#ffff00, 4:#00ffff, 5:#ff00ff, 6:#ffffff, 7:#000000
      #     plugin_languages_limit: 10
      - name: Website
        uses: lowlighter/metrics@latest
        with:
          filename: website.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: no
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://samarthtmsl.github.io/
